openapi: 3.0.0
info:
  title: Delilah Resto by Leandrouno
  description: API para restaurant 
  contact:
    email: lmugnolo@gmail.com
  version: 1.0.0
externalDocs:
  description: Github Repository
  url: https://github.com/Leandrouno/delilah_resto
servers:
  - url: http://localhost:3000/v1
tags:
  - name: Ingreso
    description: Ingreso al Sitio
  - name: Usuarios
    description: Operaciones sobre Usuarios
  - name: Productos
    description: Operaciones sobre Productos
  - name: Pedidos
    description: Operaciones sobre Pedidos

paths:
  /usuarios:
    post:
      tags:
        - Usuarios
      summary: Crear Usuario
      description: Crear un usuario en la base de datos
      operationId: crearUsuario
      requestBody:
        description: Usuario creado
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuarios"
        required: true
      security: []
      responses:
        200:
          description: Usuario Creado Correctamente
        400:
          description: Error al Crear Usuario
        409:
          description: El Usuario ya existe en la base de Datos
        500:
        description : Error

    get:
      tags:
        - Usuarios
      summary: Muestra el listado de Usuarios
      description: Muestra el listado de USuarios, se debe enviar Token
      operationId: traerInformacionUsuario
      responses:
        200:
          description: Operacion Correcta
        401:
         description: Token Invalido
        404:
         description: Usuario no Encontrado
        500:
        description : Error

    put:
      tags:
        - Usuarios
      summary: Edita un usuario
      operationId: editarUsuario
      requestBody:
        description: Fields to change
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Usuarios"
      responses:
        201:
          description: Operacion Correcta
        401:
         description: Token Invalido
        404:
         description: Usuario no Encontrado
        500:
        description : Error

    delete:
      tags:
        - Usuarios
      summary: Elimina Usuario
      responses:
       201:
          description: Operacion Correcta
      401:
         description: Token Invalido
      404:
         description: Usuario no Encontrado
      500:
        description : Error


  /ingreso:
    get:
      tags:
        - Ingreso
      security: []
      summary: Ingreso al Sistema
      operationId: loginUsuario
      parameters:
        - name: usuario
          in: query
          description: El usuario para acceder
          required: true
          schema:
            type: string
        - name: contraseña
          in: query
          description: La contraseña para acceder 
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operacion Correcta
        400:
          description: Error en Usuario o Contraseña
        500:
        description : Error
  /productos:
    get:
      tags:
        - Productos
      summary: Trae el Listado de Productos
      description: Muestra todos los productos
      operationId: traerProductos
      parameters:
        - name: busqueda
          in: query
          description: Busqueda por.
          schema:
            type: string
      responses:
        200:
          description: Operacion Correcta
        404:
         description: Producto no encontrado
        500:
        description : Error

    post:
      tags:
        - Productos
      summary: Agrega Producto
      description: Agrega producto al sistema
      operationId: agregarProducto
      requestBody:
        description: 
           required: true
      responses:
        200:
          description:Productos Agregado Correctamente
        400:
          description: Error al agregar Producto
        401:
           description: Token Invalido
        500:
          description : Error
    put:
      tags:
        - Productos
      summary: Editar un producto
      description: Edita las especificaciones de un producto
      parameters:
        - name: id
          in : body
          description: El Id del producto
          required: true
          schema:
            type: string
      operationId: editarProducto
      requestBody:
        description: 
        content:
          application/json:
           required: true
      responses:
        200:
          description: "Producto modificado Correctamente"
        400:
          description: Error al editar producto
        401:
           description: Token Invalido
        500:
          description : Error
    delete:
      tags:
        - Productos
      summary: Elimina un producto
      description: Elimina un prodcto mediante el ID
      parameters:
        - name: id
          in : body
          description: El Id del producto es necesario para eliminarlo
          required: true
          schema:
            type: string
      operationId: borrarProducto
      responses:
        200:
          description: "Producto eliminado Correctamente"
        400:
          description: Error al eliminar producto
        401:
           description: Token Invalido
        500:
          description : Error

  /pedidos:
    get:
      tags:
        - Pedidos
      summary: Trae listado de Pedidos
      description: Trae el listado de todos los Pedidos
      operationId: traerPedidos
      responses:
        200:
          description: "Operacion Correcta"
        400:
          description: "La Operacion no existe"
        401:
           description: Token Invalido
        500:
          description : Error

    post:
      tags:
        - Pedidos
      summary: Crear un Pedido
      description: Agrega una nuevo Pedido a la base de datos
      operationId: agregarPedido
      requestBody:
        description: Crear Pedido
        content:
          application/json:
            schema:
        required: true
      responses:
        200:
          description: "Pedido Creado Correctamente"
        400:
          description: "Error al crear Pedido"
        401:
           description: Token Invalido
        500:
          description : Error
    put:
      tags:
        - Pedidos
      summary: Editar un Pedido
      description: Edita un Pedido
      operationId: editarPedido
      parameters:
        - name: id
          in : body
          description: El Id del Pedido a Editar
          required: true
          schema:
            type: string
      requestBody:
        description: 
        content:
          application/json:
            schema:
              type: object
              properties:
                pedidoEstado:
                  type: string
                  example: entregada
        required: true
      responses:
        200:
          description: "Pedido Editado Correctamente"
        400:
          description: "Error al editar Pedido"
        401:
           description: Token Invalido
        500:
          description : Error
    delete:
      tags:
        - Pedidos
      summary: Eliminar un Pedido
      description: Eliminar un Pedido
      operationId: eliminarPedido
      parameters:
        - name: id
          in : body
          description: El Id del pedido a Eliminar
          required: true
          schema:
            type: string
      requestBody:
        description: 
        required: true
      responses:
        200:
          description: "Pedido Eliminado Correctamente"
        400:
          description: "Error al eliminar el Pedido"
        401:
           description: Token Invalido
        500:
          description : Error
security:
  - bearerAuth: []
